spring:
  data:
    mongodb:
      database: mobileAppBackendDb
      host: 172.20.1.225
      port: 27017
  main:
    allow-bean-definition-overriding: 'true'
  mvc:
    log-request-details: true
  application:
    name: USER-SERVICE

logging:
  level:
    org:
      springframework:
        web: DEBUG
server:
  port: 8082
  servlet:
    context-path: /msales/api/user/
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.20.1.225:8760/eureka

